apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  serviceAccountName: debug-sa
  containers:
  - name: debug-container
    image: traininghost/pipelineimage:latest
    imagePullPolicy: IfNotPresent
    command: ["/bin/bash"]
    args:
      - "-c"
      - |
        pip install --upgrade pip
        pip install cassandra-driver influxdb_client
        while true; do sleep 30; done
    env:
    - name: INFLUXDB_HOST
      value: "my-release-influxdb.default"
    - name: INFLUXDB_PORT
      value: "8086"
    - name: INFLUXDB_TOKEN
      value: ""
  restartPolicy: Never