apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  serviceAccountName: debug-sa
  containers:
  - name: debug-container
    # image: traininghost/pipelineimage:latest
    image: python:3.12.5-slim-bookworm
    imagePullPolicy: IfNotPresent
    command: ["/bin/bash", "-c"]
    args:
      - |
        cp /app_run/init_script.sh /tmp/init_script.sh &&
        chmod +x /tmp/init_script.sh &&
        /tmp/init_script.sh
        while true; do sleep 30; done
    ports:
    - containerPort: 10000
    volumeMounts:
    - name: app-volume
      mountPath: /app_run
    - name: sdk-volume
      mountPath: /SDK
    env:
    - name: INFLUXDB_HOST
      value: "my-release-influxdb.default"
    - name: INFLUXDB_PORT
      value: "8086"
    - name: INFLUXDB_TOKEN
      value: 'sPEfOtervRYoveYcQiMO'
  volumes:
  - name: app-volume
    hostPath:
      path: "/home/sdin99/workspace/Debugging"
  - name: sdk-volume
    emptyDir: {}
  restartPolicy: Never