apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kserve-test
  name: virtualservice-reader
rules:
- apiGroups: ["networking.istio.io"]
  resources: ["virtualservices"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-virtualservices
  namespace: kserve-test
subjects:
- kind: ServiceAccount
  name: debug-sa
  namespace: default
roleRef:
  kind: Role
  name: virtualservice-reader
  apiGroup: rbac.authorization.k8s.io