apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kserve-inferenceservice-reader
rules:
- apiGroups: ["serving.kserve.io"]
  resources: ["inferenceservices"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kserve-inferenceservice-reader-binding
subjects:
- kind: ServiceAccount
  name: debug-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: kserve-inferenceservice-reader
  apiGroup: rbac.authorization.k8s.io