apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kserve-test
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: kserve-test
subjects:
- kind: ServiceAccount
  name: debug-sa
  namespace: default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io